@startuml

title __SINKS's Class Diagram__\n

  namespace  {
    namespace fki.connectors.sinks {
      class dfki.connectors.sinks.SerializationFunctions {
      }
    }
  }
  

  namespace  {
    namespace fki.connectors.sinks {
      class dfki.connectors.sinks.SerializationFunctions.KeyedDataPointDataSerialization {
          + getTargetTopic()
          + serializeKey()
          + serializeValue()
      }
    }
  }
  

  namespace  {
    namespace fki.connectors.sinks {
      class dfki.connectors.sinks.SerializationFunctions.MimicWaveDataSerialization {
          + getTargetTopic()
          + serializeKey()
          + serializeValue()
      }
    }
  }
  

  namespace  {
    namespace fki.connectors.sinks {
      class dfki.connectors.sinks.SerializationFunctions.StringSerialization {
          + getTargetTopic()
          + serializeKey()
          + serializeValue()
      }
    }
  }
  

  namespace  {
    namespace fki.data {
      class dfki.data.DataPointSerializationSchema {
          + deserialize()
          + getProducedType()
          + isEndOfStream()
          + serialize()
      }
    }
  }
  

  dfki.connectors.sinks.SerializationFunctions +-down- dfki.connectors.sinks.SerializationFunctions.KeyedDataPointDataSerialization
  dfki.connectors.sinks.SerializationFunctions +-down- dfki.connectors.sinks.SerializationFunctions.MimicWaveDataSerialization
  dfki.connectors.sinks.SerializationFunctions +-down- dfki.connectors.sinks.SerializationFunctions.StringSerialization
  dfki.connectors.sinks.SerializationFunctions.KeyedDataPointDataSerialization .up.|> org.apache.flink.streaming.util.serialization.KeyedSerializationSchema
  dfki.connectors.sinks.SerializationFunctions.MimicWaveDataSerialization .up.|> org.apache.flink.streaming.util.serialization.KeyedSerializationSchema
  dfki.connectors.sinks.SerializationFunctions.StringSerialization .up.|> org.apache.flink.streaming.util.serialization.KeyedSerializationSchema
  dfki.data.DataPointSerializationSchema .up.|> org.apache.flink.api.common.serialization.DeserializationSchema
  dfki.data.DataPointSerializationSchema .up.|> org.apache.flink.api.common.serialization.SerializationSchema


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
