@startuml

title __EXAMPLES's Class Diagram__\n

  namespace  {
    namespace fki.examples {
      class dfki.examples.LSTMSequenceClassifier {
          - firstInput : String
          - firstOutput : String
          - modelFileName : String
          {static} - serialVersionUID : long
          + LSTMSequenceClassifier()
          + process()
          {static} # getInputToShape()
          {static} # getOutputToShape()
          {static} - getFirstSignature()
          {static} - getServingSignature()
      }
    }
  }
  

  namespace  {
    namespace fki.examples {
      class dfki.examples.LSTMTest {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace fki.examples {
      class dfki.examples.LSTMTest.ArrayReaderSourceFuntion {
          - directoryFileName : String
          - isRunning : boolean
          + ArrayReaderSourceFuntion()
          + cancel()
          + run()
      }
    }
  }
  

  namespace  {
    namespace fki.examples {
      class dfki.examples.LSTMTest.timeStampAssigner {
          + checkAndGetNextWatermark()
          + extractTimestamp()
      }
    }
  }
  

  namespace  {
    namespace fki.examples {
      class dfki.examples.MimicDataArrayJob {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace fki.examples {
      class dfki.examples.MimicDataJob {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace fki.examples {
      class dfki.examples.MimicDataJobOutlier {
          {static} + main()
      }
    }
  }
  

  dfki.examples.LSTMSequenceClassifier .up.|> java.io.Serializable
  dfki.examples.LSTMSequenceClassifier -up-|> org.apache.flink.streaming.api.functions.windowing.ProcessWindowFunction
  dfki.examples.LSTMTest +-down- dfki.examples.LSTMTest.ArrayReaderSourceFuntion
  dfki.examples.LSTMTest +-down- dfki.examples.LSTMTest.timeStampAssigner
  dfki.examples.LSTMTest.ArrayReaderSourceFuntion .up.|> org.apache.flink.streaming.api.functions.source.SourceFunction
  dfki.examples.LSTMTest.timeStampAssigner .up.|> org.apache.flink.streaming.api.functions.AssignerWithPunctuatedWatermarks


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
